export default {
    name:'contato',
    title:'Contato',
    type:'document',
    fields:[
        {
            name:'nome',
            title:'Nome',
            type:'string'
        },
        {
            name:'email',
            title:'Email',
            type:'string'
        },
        {
            name:'mensagem',
            title:'Mensagem',
            type:'text'
        }
    ]
}